[package]
name = "hash"
version = "0.1.0"
edition = "2021"

[dependencies]
base16ct = { version = "0.2", features = ["alloc"] }
sha2 = "0.10.8"

# diğer crate
# dependencies'leri fazla tokio vs
sha256 = "1.5.0"

